
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '804533742E787AED470D6CFB8B86FDDD'
    
_lr_action_items = {'CELL':([2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,21,22,23,24,25,26,27,28,],[3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,26,27,28,-2,]),'TRAILINGCELL':([18,],[20,]),'LEADINGCELL':([0,],[2,]),'$end':([1,20,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'trash':([6,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> LEADINGCELL CELL CELL CELL CELL trash CELL CELL CELL CELL CELL TRAILINGCELL','start',12,'p_start','project4parser.py',40),
  ('trash -> CELL CELL CELL CELL CELL CELL CELL CELL CELL CELL CELL CELL CELL CELL CELL','trash',15,'p_trash','project4parser.py',56),
]
